require ('plugins')
require ('settings')
require ('lsp')
require ('completions')
require ('keymaps')
require ('snippets')
require ('go').setup()
require ('lsp_signature')
--require ('lspconfig').pylsp.setup{}
